# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build & Install
        run: |
          python3 --version
          python3 -m pip install coverage pylint pytest
          python3 -m compileall -f pyliquibase setup.py
          python3 setup.py -q install --user
          python3 -m coverage report -m ./pyliquibase/*.py setup.py
          python3 -m coverage run --source=./tests/ -m unittest discover -s tests/
          python3 -m pylint pyliquibase setup.py

      - name: Test with Unittest
        run: |
          python3 -m coverage run --source=./tests/ -m unittest discover -s tests/
